name: COPR status

on:
  workflow_call:
    inputs:
      spec_file:
        description: Spec-file path
        required: true
        type: string

      copr_owner:
        description: COPR owner
        required: true
        type: string

      copr_project:
        description: COPR project
        required: true
        type: string

      copr_package:
        description: COPR package name
        required: true
        type: string

jobs:
  check_COPR_build_status:
    runs-on: ubuntu-latest
    name: Check copr build status
    timeout-minutes: 5
    env:
      SPEC_FILE: ${{ inputs.spec_file }}
      COPR_OWNER: ${{ inputs.copr_owner }}
      COPR_PROJECT: ${{ inputs.copr_project }}
      COPR_PACKAGE: ${{ inputs.copr_package }}

    steps:
      - name: Checkout rpm-tools
        uses: actions/checkout@v4
        with:
          repository: pvermeer/rpm-tools
          path: rpm-tools

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          path: repo

      - name: Check COPR status
        run: |
          cd repo
          ../rpm-tools/rpm-tool copr-status --disable-self-update
