name: Daily COPR status

on:
  schedule:
    - cron: "30 7 * * 1-5"
  workflow_dispatch:

jobs:
  COPR_build_status:
    uses: ./.github/workflows/copr-status.yml
    with:
      spec_file: ./rpm-tool.spec
      copr_owner: pvermeer
      copr_project: rpm-tools-test
      copr_package: rpm-tool
